# Generated by Django 5.0.6 on 2024-08-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_rename_content_conversationmessage_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='message_text',
            new_name='content',
        ),
    ]
